name: LayerForge Top Downloads Badge

on:
  schedule:
    - cron: "0 * * * *" # co godzinę
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: gh login
        run: echo "${{ secrets.SECRET_TOKEN }}" | gh auth login --with-token

      - name: Query LayerForge API 20 times and find top download
        run: |
          # Inicjalizacja zmiennych
          max_downloads=0
          top_node_json=""
          
          # Pętla pobierająca dane z API 20 razy
          for i in {1..20}; do
            echo "Pobieranie danych z próby $i..."
            curl -s https://api.comfy.org/nodes/layerforge > tmp_$i.json
            
            # Sprawdzenie czy plik JSON istnieje i jest poprawny
            if [ ! -s tmp_$i.json ] || ! jq empty tmp_$i.json 2>/dev/null; then
              echo "Błąd: Nieprawidłowy JSON dla próby $i"
              continue
            fi
            
            # Wyodrębnienie liczby pobrań i nazwy węzła
            downloads=$(jq -r '.downloads // 0' tmp_$i.json)
            name=$(jq -r '.name // ""' tmp_$i.json)
            
            # Wyświetlenie liczby pobrań dla bieżącego zapytania
            echo "Liczba pobrań dla próby $i: $downloads (węzeł: $name)"
            
            # Sprawdzenie czy liczba pobrań jest większa od dotychczasowego maksimum
            if [ "$downloads" -gt "$max_downloads" ]; then
              max_downloads=$downloads
              top_node_json=$(cat tmp_$i.json)
              echo "Nowe maksimum znalezione: $downloads"
            fi
            
            # Usunięcie tymczasowego pliku
            rm -f tmp_$i.json
          done
          
          # Zapisanie najlepszego wyniku
          if [ -n "$top_node_json" ]; then
            echo "$top_node_json" > top_layerforge.json
            echo "Najwyższa liczba pobrań: $max_downloads"
            echo "Szczegóły węzła:"
            jq . top_layerforge.json
          else
            echo "Błąd: Nie znaleziono żadnych prawidłowych danych"
            exit 1
          fi

      - name: create or update gist with top download
        id: set_id
        run: |
          if gh secret list | grep -q "LAYERFORGE_GIST_ID"
          then
              echo "GIST_ID found"
              echo "GIST=${{ secrets.LAYERFORGE_GIST_ID }}" >> $GITHUB_OUTPUT
              
              # Sprawdzenie czy gist istnieje
              if gh gist view ${{ secrets.LAYERFORGE_GIST_ID }} &>/dev/null; then
                echo "Gist istnieje, będzie zaktualizowany"
              else
                echo "Gist nie istnieje, tworzenie nowego"
                gist_id=$(gh gist create top_layerforge.json | awk -F / '{print $NF}')
                echo $gist_id | gh secret set LAYERFORGE_GIST_ID
                echo "GIST=$gist_id" >> $GITHUB_OUTPUT
              fi
          else
              echo "Tworzenie nowego gist"
              gist_id=$(gh gist create top_layerforge.json | awk -F / '{print $NF}')
              echo $gist_id | gh secret set LAYERFORGE_GIST_ID
              echo "GIST=$gist_id" >> $GITHUB_OUTPUT
          fi

      - name: create badge if needed
        run: |
          COUNT=$(jq '.downloads' top_layerforge.json)
          NAME=$(jq -r '.name' top_layerforge.json)
          if [ ! -f LAYERFORGE.md ]; then
            shields="https://img.shields.io/badge/dynamic/json?color=informational&label=TopLayerForge&query=downloads&url="
            url="https://gist.githubusercontent.com/${{ github.actor }}/${{ steps.set_id.outputs.GIST }}/raw/top_layerforge.json"
            repo="https://comfy.org"
            echo ''> LAYERFORGE.md
            echo '
            **Markdown**

            ```markdown' >> LAYERFORGE.md
            echo "[![Top LayerForge Node]($shields$url)]($repo)" >> LAYERFORGE.md
            echo '
            ```

            **HTML**
            ```html' >> LAYERFORGE.md
            echo "<a href='$repo'><img alt='Top LayerForge Node' src='$shields$url'></a>" >> LAYERFORGE.md
            echo '```' >> LAYERFORGE.md

            git add LAYERFORGE.md
            git config --global user.name "GitHub Action"
            git config --global user.email "action@github.com"
            git commit -m "Create LayerForge badge"
          fi

      - name: Update Gist
        run: |
          content=$(cat top_layerforge.json | jq -c .)
          echo '{"description": "Top LayerForge Node", "files": {"top_layerforge.json": {"content": '"$content"'}}}' > patch.json
          curl -s -X PATCH \
            --user "${{ github.actor }}:${{ secrets.SECRET_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d @patch.json https://api.github.com/gists/${{ steps.set_id.outputs.GIST }}

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
